import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './sidebar'

const inter = Inter({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        waw
        <Sidebar/>
        <div className="w-[calc(100%-300px)] ml-[300px] p-8">
        {children}
        </div>
        </body>
    </html>
  )
}
